### ISSUE TITLE
It broke again

### ISSUE THREAD

**Issue by Magnemice** [bagarrattaa/email-nuker#11]
failed to send msg
please report this error to developer
the responce reseaved from the server was: 6<!doctype html>
<html lang=en>
  <head>
    <title>urllib.error.HTTPError: HTTP Error 400: Bad Request
 // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script>
      var CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "yb6V4sIFT9CIwSJAdviS";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>HTTPError</h1>
<div class="detail">
  <p class="errormsg">urllib.error.HTTPError: HTTP Error 400: Bad Request
</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-140185929203408">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">2095</em>,
      in <code class="function">__call__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>def __call__(self, environ: dict, start_response: t.Callable) -&gt; t.Any:</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>
<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>
<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre></div>
</div>

<li><div class="frame" id="frame-140185929203072">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">2080</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws">                </span>raise</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-140185929202960">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">2077</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>error: t.Optional[BaseException] = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-140185929196912">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">1525</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre>
<pre class="line after"><span class="ws">        </span>self,</pre>
<pre class="line after"><span class="ws">        </span>rv: t.Union[ResponseReturnValue, HTTPException],</pre></div>
</div>

<li><div class="frame" id="frame-140185929449536">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">1523</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>self.try_trigger_before_first_request_functions()</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(</pre></div>
</div>

<li><div class="frame" id="frame-140185929449648">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/flask/app.py"</cite>,
      line <em class="line">1509</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>getattr(rule, &quot;provide_automatic_options&quot;, False)</pre>
<pre class="line before"><span class="ws">            </span>and req.method == &quot;OPTIONS&quot;</pre>
<pre class="line before"><span class="ws">        </span>):</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line current"><span class="ws">        </span>return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self) -&gt; Response:</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-140185929449760">
  <h4>File <cite class="filename">"/data/bomber2.py"</cite>,
      line <em class="line">56</em>,
      in <code class="function">bomb6</code></h4>
  <div class="source "><pre class="line before"><span class="ws">    </span>a5.send(to=t,subject=s,contents=m)</pre>
<pre class="line before"><span class="ws">    </span>return &quot;Sent&quot;</pre>
<pre class="line before"><span class="ws"></span>@app.route(&quot;/6/bomb/&lt;string:t&gt;/&lt;string:s&gt;/&lt;string:m&gt;&quot;)</pre>
<pre class="line before"><span class="ws"></span>def bomb6(t,s,m):</pre>
<pre class="line before"><span class="ws">    </span>time.sleep(delay)</pre>
<pre class="line current"><span class="ws">    </span>a6.send(to=t,subject=s,contents=m)</pre>
<pre class="line after"><span class="ws">    </span>return &quot;Sent&quot;</pre>
<pre class="line after"><span class="ws"></span>@app.route(&quot;/7/bomb/&lt;string:t&gt;/&lt;string:s&gt;/&lt;string:m&gt;&quot;)</pre>
<pre class="line after"><span class="ws"></span>def bomb7(t,s,m):</pre>
<pre class="line after"><span class="ws">    </span>time.sleep(delay)</pre>
<pre class="line after"><span class="ws">    </span>a7.send(to=t,subject=s,contents=m)</pre></div>
</div>

<li><div class="frame" id="frame-140185929449872">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/sender.py"</cite>,
      line <em class="line">156</em>,
      in <code class="function">send</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>prettify_html=True,</pre>
<pre class="line before"><span class="ws">        </span>message_id=None,</pre>
<pre class="line before"><span class="ws">        </span>group_messages=True,</pre>
<pre class="line before"><span class="ws">    </span>):</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot; Use this to send an email with gmail&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>self.login()</pre>
<pre class="line after"><span class="ws">        </span>recipients, msg_bytes = self.prepare_send(</pre>
<pre class="line after"><span class="ws">            </span>to,</pre>
<pre class="line after"><span class="ws">            </span>subject,</pre>
<pre class="line after"><span class="ws">            </span>contents,</pre>
<pre class="line after"><span class="ws">            </span>attachments,</pre></div>
</div>

<li><div class="frame" id="frame-140185929449984">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/sender.py"</cite>,
      line <em class="line">208</em>,
      in <code class="function">login</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>except (TypeError, AttributeError, smtplib.SMTPServerDisconnected):</pre>
<pre class="line before"><span class="ws">            </span>pass</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def login(self):</pre>
<pre class="line before"><span class="ws">        </span>if self.oauth2_file is not None:</pre>
<pre class="line current"><span class="ws">            </span>self._login_oauth2(self.credentials)</pre>
<pre class="line after"><span class="ws">        </span>else:</pre>
<pre class="line after"><span class="ws">            </span>self._login(self.credentials)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def _login(self, password):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;</pre></div>
</div>

<li><div class="frame" id="frame-140185929450096">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/sender.py"</cite>,
      line <em class="line">248</em>,
      in <code class="function">_login_oauth2</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>self.smtp = self.connection(self.host, self.port, **self.kwargs)</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>self.smtp.set_debuglevel(self.debuglevel)</pre>
<pre class="line before"><span class="ws">        </span>except AttributeError:</pre>
<pre class="line before"><span class="ws">            </span>pass</pre>
<pre class="line current"><span class="ws">        </span>auth_string = self.get_oauth_string(self.user, oauth2_info)</pre>
<pre class="line after"><span class="ws">        </span>self.smtp.ehlo(oauth2_info[&quot;google_client_id&quot;])</pre>
<pre class="line after"><span class="ws">        </span>if self.starttls is True:</pre>
<pre class="line after"><span class="ws">            </span>self.smtp.starttls()</pre>
<pre class="line after"><span class="ws">        </span>self.smtp.docmd(&quot;AUTH&quot;, &quot;XOAUTH2 &quot; + auth_string)</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140185929450208">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/sender.py"</cite>,
      line <em class="line">238</em>,
      in <code class="function">get_oauth_string</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>def handle_password(user, password):</pre>
<pre class="line before"><span class="ws">        </span>return handle_password(user, password)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>@staticmethod</pre>
<pre class="line before"><span class="ws">    </span>def get_oauth_string(user, oauth2_info):</pre>
<pre class="line current"><span class="ws">        </span>return get_oauth_string(user, oauth2_info)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def _login_oauth2(self, oauth2_info):</pre>
<pre class="line after"><span class="ws">        </span>if &quot;email_address&quot; in oauth2_info:</pre>
<pre class="line after"><span class="ws">            </span>oauth2_info.pop(&quot;email_address&quot;)</pre>
<pre class="line after"><span class="ws">        </span>self.smtp = self.connection(self.host, self.port, **self.kwargs)</pre></div>
</div>

<li><div class="frame" id="frame-140185929450320">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py"</cite>,
      line <em class="line">96</em>,
      in <code class="function">get_oauth_string</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>response = call_refresh_token(google_client_id, google_client_secret, google_refresh_token)</pre>
<pre class="line before"><span class="ws">    </span>return response[&#x27;access_token&#x27;], response[&#x27;expires_in&#x27;]</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>def get_oauth_string(user, oauth2_info):</pre>
<pre class="line current"><span class="ws">    </span>access_token, expires_in = refresh_authorization(**oauth2_info)</pre>
<pre class="line after"><span class="ws">    </span>auth_string = generate_oauth2_string(user, access_token, as_base64=True)</pre>
<pre class="line after"><span class="ws">    </span>return auth_string</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>def get_oauth2_info(oauth2_file):</pre></div>
</div>

<li><div class="frame" id="frame-140185929450432">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py"</cite>,
      line <em class="line">91</em>,
      in <code class="function">refresh_authorization</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>response = call_authorize_tokens(google_client_id, google_client_secret, authorization_code)</pre>
<pre class="line before"><span class="ws">    </span>return response[&#x27;refresh_token&#x27;], response[&#x27;access_token&#x27;], response[&#x27;expires_in&#x27;]</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>def refresh_authorization(google_client_id, google_client_secret, google_refresh_token):</pre>
<pre class="line current"><span class="ws">    </span>response = call_refresh_token(google_client_id, google_client_secret, google_refresh_token)</pre>
<pre class="line after"><span class="ws">    </span>return response[&#x27;access_token&#x27;], response[&#x27;expires_in&#x27;]</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>def get_oauth_string(user, oauth2_info):</pre>
<pre class="line after"><span class="ws">    </span>access_token, expires_in = refresh_authorization(**oauth2_info)</pre></div>
</div>

<li><div class="frame" id="frame-140185929450544">
  <h4>File <cite class="filename">"/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py"</cite>,
      line <em class="line">71</em>,
      in <code class="function">call_refresh_token</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>params[&#x27;client_secret&#x27;] = client_secret</pre>
<pre class="line before"><span class="ws">    </span>params[&#x27;refresh_token&#x27;] = refresh_token</pre>
<pre class="line before"><span class="ws">    </span>params[&#x27;grant_type&#x27;] = &#x27;refresh_token&#x27;</pre>
<pre class="line before"><span class="ws">    </span>request_url = command_to_url(&#x27;o/oauth2/token&#x27;)</pre>
<pre class="line before"><span class="ws">    </span>encoded_params = urlencode(params).encode(&#x27;UTF-8&#x27;)</pre>
<pre class="line current"><span class="ws">    </span>response = urlopen(request_url, encoded_params).read().decode(&#x27;UTF-8&#x27;)</pre>
<pre class="line after"><span class="ws">    </span>return json.loads(response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>def generate_oauth2_string(username, access_token, as_base64=False):</pre>
<pre class="line after"><span class="ws">    </span>auth_string = &#x27;user=%s\1auth=Bearer %s\1\1&#x27; % (username, access_token)</pre></div>
</div>

<li><div class="frame" id="frame-140185929450656">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">216</em>,
      in <code class="function">urlopen</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>opener = build_opener(https_handler)</pre>
<pre class="line before"><span class="ws">    </span>elif _opener is None:</pre>
<pre class="line before"><span class="ws">        </span>_opener = opener = build_opener()</pre>
<pre class="line before"><span class="ws">    </span>else:</pre>
<pre class="line before"><span class="ws">        </span>opener = _opener</pre>
<pre class="line current"><span class="ws">    </span>return opener.open(url, data, timeout)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>def install_opener(opener):</pre>
<pre class="line after"><span class="ws">    </span>global _opener</pre>
<pre class="line after"><span class="ws">    </span>_opener = opener</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140185929450768">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">525</em>,
      in <code class="function">open</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span># post-process response</pre>
<pre class="line before"><span class="ws">        </span>meth_name = protocol+&quot;_response&quot;</pre>
<pre class="line before"><span class="ws">        </span>for processor in self.process_response.get(protocol, []):</pre>
<pre class="line before"><span class="ws">            </span>meth = getattr(processor, meth_name)</pre>
<pre class="line current"><span class="ws">            </span>response = meth(req, response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def _open(self, req, data=None):</pre>
<pre class="line after"><span class="ws">        </span>result = self._call_chain(self.handle_open, &#x27;default&#x27;,</pre></div>
</div>

<li><div class="frame" id="frame-140185929450880">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">634</em>,
      in <code class="function">http_response</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>code, msg, hdrs = response.code, response.msg, response.info()</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span># According to RFC 2616, &quot;2xx&quot; code indicates that the client&#x27;s</pre>
<pre class="line before"><span class="ws">        </span># request was successfully received, understood, and accepted.</pre>
<pre class="line before"><span class="ws">        </span>if not (200 &lt;= code &lt; 300):</pre>
<pre class="line current"><span class="ws">            </span>response = self.parent.error(</pre>
<pre class="line after"><span class="ws">                </span>&#x27;http&#x27;, request, response, code, msg, hdrs)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>https_response = http_response</pre></div>
</div>

<li><div class="frame" id="frame-140185929450992">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">563</em>,
      in <code class="function">error</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>if result:</pre>
<pre class="line before"><span class="ws">            </span>return result</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>if http_err:</pre>
<pre class="line before"><span class="ws">            </span>args = (dict, &#x27;default&#x27;, &#x27;http_error_default&#x27;) + orig_args</pre>
<pre class="line current"><span class="ws">            </span>return self._call_chain(*args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span># XXX probably also want an abstract factory that knows when it makes</pre>
<pre class="line after"><span class="ws"></span># sense to skip a superclass in favor of a subclass and when it might</pre>
<pre class="line after"><span class="ws"></span># make sense to include both</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140185929451104">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">496</em>,
      in <code class="function">_call_chain</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span># the request, or return None if they can&#x27;t but another handler</pre>
<pre class="line before"><span class="ws">        </span># could.  Otherwise, they return the response.</pre>
<pre class="line before"><span class="ws">        </span>handlers = chain.get(kind, ())</pre>
<pre class="line before"><span class="ws">        </span>for handler in handlers:</pre>
<pre class="line before"><span class="ws">            </span>func = getattr(handler, meth_name)</pre>
<pre class="line current"><span class="ws">            </span>result = func(*args)</pre>
<pre class="line after"><span class="ws">            </span>if result is not None:</pre>
<pre class="line after"><span class="ws">                </span>return result</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def open(self, fullurl, data=None, timeout=socket._GLOBAL_DEFAULT_TIMEOUT):</pre>
<pre class="line after"><span class="ws">        </span># accept a URL or a Request object</pre></div>
</div>

<li><div class="frame" id="frame-140185929451216">
  <h4>File <cite class="filename">"/usr/lib/python3.10/urllib/request.py"</cite>,
      line <em class="line">643</em>,
      in <code class="function">http_error_default</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>https_response = http_response</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws"></span>class HTTPDefaultErrorHandler(BaseHandler):</pre>
<pre class="line before"><span class="ws">    </span>def http_error_default(self, req, fp, code, msg, hdrs):</pre>
<pre class="line current"><span class="ws">        </span>raise HTTPError(req.full_url, code, msg, hdrs, fp)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>class HTTPRedirectHandler(BaseHandler):</pre>
<pre class="line after"><span class="ws">    </span># maximum number of redirections to any single URL</pre>
<pre class="line after"><span class="ws">    </span># this is needed because of the state that cookies introduce</pre>
<pre class="line after"><span class="ws">    </span>max_repeats = 4</pre></div>
</div>
</ul>
  <blockquote>urllib.error.HTTPError: HTTP Error 400: Bad Request
</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 2080, in wsgi_app
    response = self.handle_exception(e)
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File &quot;/usr/local/lib/python3.10/dist-packages/flask/app.py&quot;, line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File &quot;/data/bomber2.py&quot;, line 56, in bomb6
    a6.send(to=t,subject=s,contents=m)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/sender.py&quot;, line 156, in send
    self.login()
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/sender.py&quot;, line 208, in login
    self._login_oauth2(self.credentials)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/sender.py&quot;, line 248, in _login_oauth2
    auth_string = self.get_oauth_string(self.user, oauth2_info)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/sender.py&quot;, line 238, in get_oauth_string
    return get_oauth_string(user, oauth2_info)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py&quot;, line 96, in get_oauth_string
    access_token, expires_in = refresh_authorization(**oauth2_info)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py&quot;, line 91, in refresh_authorization
    response = call_refresh_token(google_client_id, google_client_secret, google_refresh_token)
  File &quot;/usr/local/lib/python3.10/dist-packages/yagmail/oauth2.py&quot;, line 71, in call_refresh_token
    response = urlopen(request_url, encoded_params).read().decode(&#x27;UTF-8&#x27;)
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 216, in urlopen
    return opener.open(url, data, timeout)
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 525, in open
    response = meth(req, response)
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 634, in http_response
    response = self.parent.error(
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 563, in error
    return self._call_chain(*args)
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 496, in _call_chain
    result = func(*args)
  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

**Comment by raphaelsimon1** [comment]
Keeps breaking after 5-10 messages on any platform MacOs or Kali

What is the resolution for that?

**Comment by bagarrattaa** [comment]
@Magnemice issue fixed

**Comment by raphaelsimon1** [comment]
Many thanks for your response and care – What is that mean?

***@***.***

From: Raphael Simon ***@***.***>
Date: Wednesday, June 22, 2022 at 3:41 PM
To: bagarrattaa/email-nuker ***@***.***>, bagarrattaa/email-nuker ***@***.***>
Cc: Comment ***@***.***>
Subject: Re: [bagarrattaa/email-nuker] It broke again (Issue #11)

Same same.

What could be the issue?

***@***.***

From: rfeferfefe ***@***.***>
Reply-To: bagarrattaa/email-nuker ***@***.***>
Date: Wednesday, June 22, 2022 at 2:49 PM
To: bagarrattaa/email-nuker ***@***.***>
Cc: raphaelsimon1 ***@***.***>, Comment ***@***.***>
Subject: Re: [bagarrattaa/email-nuker] It broke again (Issue #11)


@Magnemice<https://github.com/Magnemice> issue fixed

**Comment by raphaelsimon1** [comment]
Same issue - What is your recommendation? work it out on Kali or MacOs? both gives the same error.
