### ISSUE TITLE
Tbomb isn't working 

### ISSUE THREAD

**Issue by ghostjoyprokash** [bagarrattaa/email-nuker#27]
![Screenshot_2023-08-27-12-11-02-71_84d3000e3f4017145260f7618db1d683](https://github.com/bagarrattaa/email-nuker/assets/143306862/1db4cb89-cf9f-46f1-85b7-5ba9c2830793)

**Comment by se7enthsinvii** [comment]
Can confirm

**Comment by bagarrattaa** [comment]
bomb is not my bomber. my bomber is email-nuker (https://emailnuker.onrender.com/)
