### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by ghost** [bagarrattaa/email-nuker#28]
Hi!

Regularly this appears:
![IMG_0628](https://github.com/bagarrattaa/email-nuker/assets/146885455/8ca8878d-c974-4e2c-afdf-b512ef9fdf5c)

Also…

>Because of that, google doesn't let me create email accounts without a phone number, otherwise they would be either banned (as long as all the accounts associated) or disabled

You can use hidemyna.me vpn to bypass it. There IP is pretty clean. They give you a free 24 hour trial, but you can bypass it by new email accounts and new ip

**Comment by bagarrattaa** [comment]
Currently, I have a plenty of gmail ids in stock. For like a long time, maybe 7-8 months, I have made 0 gmail ids by myself. I am getting enough of gmail ids from premium upgrades and i also buy Gmail ids using crypto which I recieve by giving people premium access keys. I just can't add too many Gmail ids so easily as i have to first change password, add recover email id, get refresh token of account using client id and client secret. I think I have to spend atleast 6-7 minutes on each account. I will use that vpn app when people stop buying premium @ghost @lodembeep
