### ISSUE TITLE
emailnukerweb.onrender.com stopped working

### ISSUE THREAD

**Issue by 68HI98** [bagarrattaa/email-nuker#29]
Hello!

Your web app stopped working. Can you fix it?

@bagarrattaa

**Comment by profesionalleet1337** [comment]
yeah, also for me the site don't work from 3 days ? 

@bagarrattaa

**Comment by Hgfugefu** [comment]
4 days. @bagarrattaa

**Comment by bagarrattaa** [comment]
https://awesomeprojects.onrender.com will be new website, and shall start working in max 12 hours. I suspect that some people were either reporting website or it was automated website ban due nuker in its link @profesionalleet1337 @68HI98 @lodembeep
