### ISSUE TITLE
From some days, doesn't work

### ISSUE THREAD

**Issue by profesionalleet1337** [bagarrattaa/email-nuker#32]
Hey, the site is down from some days ? First when I found this git, i tried it, and work's perfect. But in the next day, nothing's work's till now. Will it be fixed ? : )

**Comment by bagarrattaa** [comment]
https://awesomeprojects.onrender.com will be new website, and shall start working in max 12 hours. I suspect that some people were either reporting website or it was automated website ban due nuker in its link

**Comment by bagarrattaa** [comment]
@profesionalleet1337
