### ISSUE TITLE
failed to send msg

### ISSUE THREAD

**Issue by w4kened** [bagarrattaa/email-nuker#4]
failed to send msg
please report this error to developer
the responce reseaved from the server was: 3<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Comment by bagarrattaa** [comment]
so this is the current issue 


Your account has been disabled
apple.macos.ios.11@gmail.com
It looks as though this account was associated with multiple other accounts, or created by a program, and used to violate Google’s policies. Learn more
If you think that your account was disabled by mistake, request a review of this decision as soon as possible.
We understand that what's in your account is important, so you can also download your data for some Google services.

    HelpPrivacyTerms




some gmail ids which this bomber uses have been disabled by google 

I will create more gmail ids and add in bomber

**Comment by bagarrattaa** [comment]
please try latest version 
all issues have been fixed
