### ISSUE TITLE
Error after a couple messages

### ISSUE THREAD

**Issue by Magnemice** [bagarrattaa/email-nuker#7]
failed to send msg
please report this error to developer
the responce reseaved from the server was: 20<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by bagarrattaa** [comment]
@Magnemice issue fixed
